// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200815181353_InitialActivitySeed")]
    partial class InitialActivitySeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8fcca202-d66f-4128-abd9-e8fcbec22c91"),
                            Category = "a",
                            City = "London",
                            Date = new DateTime(2021, 4, 15, 15, 13, 53, 693, DateTimeKind.Local).AddTicks(3884),
                            Description = "Description",
                            Title = "Future Activity 8",
                            Venue = "Cinema"
                        },
                        new
                        {
                            Id = new Guid("066f3953-f4ba-480b-86ce-a69443b7eb3d"),
                            Category = "b",
                            City = "London",
                            Date = new DateTime(2021, 4, 15, 15, 13, 53, 694, DateTimeKind.Local).AddTicks(3375),
                            Description = "Description",
                            Title = "Future Activity 8",
                            Venue = "Cinema"
                        },
                        new
                        {
                            Id = new Guid("f87aaf0d-7362-441d-b951-4eff78225743"),
                            Category = "c",
                            City = "London",
                            Date = new DateTime(2021, 4, 15, 15, 13, 53, 694, DateTimeKind.Local).AddTicks(3432),
                            Description = "Description",
                            Title = "Future Activity 8",
                            Venue = "Cinema"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
